using Day6;

namespace UnitTests.Days;

[TestClass]
public class Day6Tests
{
    [TestMethod]
    public void TestFirstChallenge()
    {
        const string map = """
                           ....#.....
                           .........#
                           ..........
                           ..#.......
                           .......#..
                           ..........
                           .#..^.....
                           ........#.
                           #.........
                           ......#...
                           """;

        Assert.AreEqual(41, Challenges.FirstChallenge(map));
    }

    [TestMethod]
    public void TestSecondChallenge()
    {
        const string map = """
                           ....#.....
                           .........#
                           ..........
                           ..#.......
                           .......#..
                           ..........
                           .#..^.....
                           ........#.
                           #.........
                           ......#...
                           """;

        Assert.AreEqual(6, Challenges.SecondChallenge(map));
    }
}