using Day8;

namespace UnitTests.Days;

[TestClass]
public class Day8Tests
{
    [TestMethod]
    public void TestPart1()
    {
        const string test = """
                            ............
                            ........0...
                            .....0......
                            .......0....
                            ....0.......
                            ......A.....
                            ............
                            ............
                            ........A...
                            .........A..
                            ............
                            ............
                            """;

        Assert.AreEqual(14, Challenges.Part1(test));
    }
    
    [TestMethod]
    public void TestPart2()
    {
        const string test = """
                            ............
                            ........0...
                            .....0......
                            .......0....
                            ....0.......
                            ......A.....
                            ............
                            ............
                            ........A...
                            .........A..
                            ............
                            ............
                            """;

        Assert.AreEqual(34, Challenges.Part2(test));
    }
}